ExpressVoitures/Controllers/CarsController.cs
using ExpressVoitures.Models.ViewModels;
using ExpressVoitures.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExpressVoitures.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarService _carService;

        public CarsController(ICarService carService)
        {
            this._carService = carService;
        }

        // GET: Cars
        public ViewResult Index()
        {
            return View(this._carService.GetAll());
        }

        // GET: Cars/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = this._carService.GetById(id.Value);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

		[Authorize(Roles = "Admin")]
		// GET: Cars/Create
		public IActionResult Create()
        {
            var carModel = new CarModel { Year = 1990, DateOfBuy = DateTime.Today };
            return View(carModel);
        }

		[Authorize(Roles = "Admin")]
		// POST: Cars/Create
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CarModel carModel)
        {
            if (ModelState.IsValid)
            {
                this._carService.Add(carModel);
                this._carService.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(carModel);
        }

		[Authorize(Roles = "Admin")]
		// GET: Cars/Edit/5
		public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = this._carService.GetById(id.Value);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

		[Authorize(Roles = "Admin")]
		// POST: Cars/Edit/5
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CarModel carModel)
        {
            if (id != carModel.IdCar)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this._carService.Update(carModel);
                    this._carService.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(carModel.IdCar))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carModel);
        }

		[Authorize(Roles = "Admin")]
		// GET: Cars/Delete/5
		public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = this._carService.GetById(id.Value);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

		[Authorize(Roles = "Admin")]
		// POST: Cars/Delete/5
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, CarModel carModel)
        {
            if (id != carModel.IdCar)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this._carService.Delete(carModel);
                    this._carService.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(carModel.IdCar))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool CarExists(int id)
        {
            return this._carService.GetById(id) != null;
        }
    }
}

ExpressVoitures/Controllers/CarsForSaleController.cs
using ExpressVoitures.Models.ViewModels;
using ExpressVoitures.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExpressVoitures.Controllers
{
    public class CarsForSaleController : Controller
    {
        private readonly ICarForSaleService _carForSaleService;

        public CarsForSaleController(ICarForSaleService carForSaleService)
        {
            this._carForSaleService = carForSaleService;
        }

        // GET: CarsForSale
        public IActionResult Index()
        {
            return View(this._carForSaleService.GetAll());
        }

        // GET: CarsForSale/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carForSale = this._carForSaleService.GetById(id.Value);
            if (carForSale == null)
            {
                return NotFound();
            }

            return View(carForSale);
        }

		// GET: CarsForSale/Create
		[Authorize(Roles = "Admin")]
		public IActionResult Create()
        {
            var viewModel = new CarForSaleModel()
            {
                DateOfAvailabilityForSale = DateTime.Today,
                Cars = _carForSaleService.GetCarsAvailable()
            };

            return View(viewModel);
        }

		// POST: CarsForSale/Create
		[Authorize(Roles = "Admin")]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CarForSaleModel carForSaleModel)
        {
            if (ModelState.IsValid)
            {
                this._carForSaleService.Add(carForSaleModel, null);
                this._carForSaleService.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(carForSaleModel);
        }

		// GET: CarsForSale/Edit/5
		[Authorize(Roles = "Admin")]
		public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carForSaleModel = this._carForSaleService.GetById(id.Value);
            if (carForSaleModel == null)
            {
                return NotFound();
            }
            return View(carForSaleModel);
        }

		// POST: CarsForSale/Edit/5
		[Authorize(Roles = "Admin")]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CarForSaleModel carForSaleModel)
        {
            if (id != carForSaleModel.IdCarForSale)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this._carForSaleService.Update(carForSaleModel);
                    this._carForSaleService.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarForSaleExists(carForSaleModel.IdCarForSale))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carForSaleModel);
        }

		// GET: CarsForSale/Delete/5
		[Authorize(Roles = "Admin")]
		public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carForSale = this._carForSaleService.GetById(id.Value);
            if (carForSale == null)
            {
                return NotFound();
            }
            return View(carForSale);
        }

		// POST: CarsForSale/Delete/5
		[Authorize(Roles = "Admin")]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, CarForSaleModel carForSaleModel)
        {
            if (id != carForSaleModel.IdCarForSale)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this._carForSaleService.Delete(carForSaleModel);
                    this._carForSaleService.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarForSaleExists(carForSaleModel.IdCarForSale))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool CarForSaleExists(int id)
        {
            return this._carForSaleService.GetById(id) != null;
        }
    }
}

ExpressVoitures/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Express Voitures</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpressVoitures.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Inventaire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarsForSale" asp-action="Index">Voitures en vente</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Express Voitures
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>